version: '3'
services:
  docker-compose-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - spring-boot-mysql-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:3000
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-compose-mysql
    networks:
      - spring-boot-mysql-network

  movies:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-compose-mysql
    networks:
      - spring-boot-mysql-network

networks:
  spring-boot-mysql-network:
    driver: bridge